version: 0.0
os: linux
files:
  - source: /
    destination: /tmp
hooks:
  # before the application revision is downloaded
  # gracefully stop the current application or remove currently installed packages
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 10
      runas: root
  
  # after new files are downloaded in codedeploy tmp folder, use this for preinstall tasks
  # such as install dependencies, decrypting files and creating a backup
  # can't run scripts against codedeploy tmp folder
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 10
      runas: ec2-user

  # after files are copied to your destination folder, use this for setting some env vars or
  # changing file permissions, or creating some directories
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 10
      runas: ec2-user
  
  # use this to start application with latest version files
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 30
      runas: ec2-user
  
  # use this to validate if app started correctly such as curl GET /index.html is 200
  # or service status 
  ValidateService:
    - location: scripts/validate.sh
      timeout: 10
